language: python
python:
  - "2.7"
  - "3.4"

install: 'pip install -r requirements.txt'

script: py.test -v

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

services:
  - postgresql
